<?php
	$str = '{
		    "status": "ok",
				    "datas": {
						        "UserId": "11281647",
								        "UserName": "mobile13381717860",
										        "UserPhoto": "8269c64a8604054073d41f35cdf5e751",
												        "NickName": "",
														        "TrueName": "王奇",
																        "UserSex": "1",
																		        "UserMobile": "13381717860",
																				        "IsOpen": "0",
																						        "Signature": null,
																								        "commid": "0",
																										        "OtherAddr": "",
																												        "FromType": "0",
																														        "updateDate": "1414478083",
																																        "CityId": "0",
																																		        "host": "1",
																																				        "mobile_verify": "1",
																																						        "Wealth": "0",
																																								        "UserBirthday": "1993-09-03",
																																										        "update_time": "2014-10-29 11:25:34",
																																												        "has_password": "1",
																																														        "nick_name_pinyin": "",
																																																        "UserPwd": "MTAzMmI2NzFiMThlMWQ5ZDZlYjJkOTlhZjA0MzRmZDY=",
																																																		        "UserPhone": "13381717860",
																																																				        "UserAddress": null,
																																																						        "UserEmail": "www.670358101@qq.com",
																																																								        "EmailPass": "0",
																																																										        "UserType": "9",
																																																												        "RegDate": "1414478083",
																																																														        "LastLogDate": "1415267806",
																																																																        "LogTimes": "33",
																																																																		        "ClientIP": "101.228.133.11",
																																																																				        "NameUpper": null,
																																																																						        "WorkerNum": "",
																																																																								        "TestAccount": "1",
																																																																										        "Points": "0",
																																																																												        "YearPoint": "0",
																																																																														        "Fuid": "0",
																																																																																        "CurrentCity": "0",
																																																																																		        "registerFrom": "",
																																																																																				        "updated_datetime": "2014-11-06 17:56:46",
																																																																																						        "isInUse": "1"
																																																																																									    },
					    "error_message": "",
						    "error_code": 0
	}';

print_r(json_decode($str,1));
